### PR TITLE
Gameplay Guide and Cheat Codes

### PR DESCRIPTION
**Pull request by DamianSuess**
@sinshu I created a `GamePlay.md` file which contains a quick Gettings Started of which `WAD` files are acceptable, keyboard mapping, and cheat codes.

If you think something should be updated or if this file isn't necessary, let me know.

Love your port of Doom. Great job!

### CODE REVIEW

**Comment by DamianSuess** [comment]
I synced up the branch. Is there anything else that you would like to see added/changed in this PR?

**Comment by IceReaper** [comment]
No offence, but to me it looks like this PR is purely made to get some github badges as quick as possible without actualy earning them?
The project itself wont need a generic doom manual, as it could simply link the doom wiki.

Anyways:
- There is no anchored index
- PLTONIA:WAD is called PLUTONIA.WAD
- The Plutonia Experiment and TNT Evilution came as a final doom bundle, but in the list i would use their actual names
- You completely missed free doom
- The default keybindings are pretty self explaining and common to any game. Additionally they can be altered
- You missed the F1 help screen key, which shows most you wrote in your document
- Mouse button 2 is not move forward and use at the same time
- Even the cheat list is copy pasted, as this port does not have the IDMYPOS cheat
- There might be even more mistakes as i just did a quick look over the diff

There are human readable code pieces in this repo where to find
- which wads are supported
- what the keybindings are
- which cheats are implemented

@sinshu i would vote to reject this PR as its obviously simply a badge-grab, and despite not even going through the effort of the tiniest bit of research and contributing a document which mimics what this project actualy includes. IMO this is extremely disrespectful to the project as well as to any developer earning their badges.

**Comment by DamianSuess** [comment]
GitHub badges? Not everyone in this world is out for some participation trophy. There are a lot of us out there that just want to help.

**Comment by sinshu** [comment]
@DamianSuess
Thanks for the PR. I appreciate your willingness to help. However, IceReaper's points about the issues with the PR are valid. Please make sure to understand the project better before your next contribution.

@IceReaper
Thanks for pointing out the issues with the PR.

**Comment by DamianSuess** [comment]
@sinshu No worries. The PR intended to humbly assist with documentation to help get new/legacy players started. Not playing the game in 20-30 years, it's easy to forget the keys.

I cannot deny the joy we got playing this.

Thank you for the hard work put into this amazing port. Keep it up 😃

**Pull request closed without merging**
