### PR TITLE
Upgraded project to .NET 5

### PR DESCRIPTION
**Pull request by MoienTajik**
- Added proper gitignore file for .NET projects to the solution
- Upgraded projects to .NET 5
- Updated test project Nuget packages to the latest version

### CODE REVIEW

**Comment by IceReaper** [comment]
That gitignore looks quite bloated tbh.

**Comment by MoienTajik** [comment]
Actually it's created from [VisualStudio.gitignore](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore) and [gitignore.io](https://www.toptal.com/developers/gitignore)'s standard `csharp` template.

**Comment by sinshu** [comment]
Adding gitignore and updating the test project look fine.
However, since .NET 5 is still under development, I want to keep the current version.

**Comment by MoienTajik** [comment]
hmm, .NET 5 is now in RC mode as announced [here](https://devblogs.microsoft.com/dotnet/announcing-net-5-0-rc-1).
I think it can be used as the main SDK at least from now.

**Pull request merged**
